version: '3.8'

services:
  openlist-strm:
    image: openlist-strm:latest
    container_name: openlist-strm
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # Configuration file
      - ./config.yaml:/app/configs/config.yaml:ro

      # Data persistence
      - ./data:/app/data

      # Logs
      - ./logs:/app/logs

      # STRM output directory (mount your media library path here)
      - /path/to/your/strm:/mnt/strm
    environment:
      # 时区设置
      - TZ=Asia/Shanghai

      # 用户权限设置（与宿主机用户匹配，避免权限问题）
      # 获取当前用户 UID: id -u
      # 获取当前用户 GID: id -g
      - PUID=1000
      - PGID=1000
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    networks:
      - openlist-strm-network

networks:
  openlist-strm-network:
    driver: bridge
