# OpenList-STRM Configuration Example

# Server configuration
server:
  host: "0.0.0.0"
  port: 8080

# Alist configuration
alist:
  url: "http://localhost:5244"
  token: "your-alist-token-here"
  sign_enabled: false
  timeout: 30  # seconds

# Note: Path mappings are now managed via Web UI and stored in database
# Use the Web UI (http://localhost:8080) to create and manage your mappings

# Note: Schedule tasks are now configured per-mapping in Web UI
# Each mapping can have its own cron expression for automatic execution

# API configuration
api:
  enabled: true
  token: ""  # Optional: set API token for authentication
  timeout: 300  # seconds

# Web UI configuration
web:
  enabled: true
  username: "admin"  # Not used in current version
  password: "admin123"  # Not used in current version

# Logging configuration
log:
  level: "info"  # debug, info, warn, error
  file: ""  # Empty string outputs to stdout (recommended for Docker)
            # Set to "./logs/openlist-strm.log" for file logging
  max_size: 100  # MB
  max_backups: 3

# Database configuration
database:
  path: "./data/openlist-strm.db"
