name: Backend CI

on:
  push:
    branches: [ master, main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ master, main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache-dependency-path: backend/go.sum

    - name: Get dependencies
      working-directory: ./backend
      run: go mod download

    - name: Run go vet
      working-directory: ./backend
      run: go vet ./...

    - name: Build
      working-directory: ./backend
      run: go build -v -o bin/openlist-strm ./cmd/server

    - name: Run tests
      working-directory: ./backend
      run: go test -v -race -coverprofile=coverage.out ./... || echo "No tests found"

    - name: Upload coverage
      if: success()
      uses: codecov/codecov-action@v4
      with:
        files: ./backend/coverage.out
        flags: backend
        fail_ci_if_error: false

  lint:
    name: Code Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        working-directory: backend
        args: --timeout=5m
